### PR TITLE
- Support for template_dir setting.

### PR DESCRIPTION
**Pull request by solcre**
Hi, I would like to add support for the template_dir settings.

### CODE REVIEW

**Comment by gkralik** [comment]
I'll take a look in the evening.

**Comment by solcre** [comment]
any news on this? :S

**Comment by gkralik** [comment]
I don't see why this change would be necessary, as you can set the `template_dir` already:
```php
'gk_smarty' => [
    'smarty_options' => [
        'template_dir' => '<put dir here>',
    ],
]
```
The relevant code is [here](https://github.com/gkralik/gk-smarty/blob/master/src/GkSmarty/View/SmartyRendererFactory.php#L33-L45)

**Comment by solcre** [comment]
Cool didn't see that, why compile dir and cache dir have their own setters instead of using smarty_options also ?

**Comment by gkralik** [comment]
That's just a leftover from the very start of the module. I just don't want to remove these two settings now, as that would have the potential to break a lot of things depending on the keys ;)

`smarty_options` is the more generic configuration key, as you can configure nearly all Smarty options through it.

**Pull request closed without merging**
